---
- name: Create Logstash configuration files.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: logstash
    group: logstash
    mode: 0644
  with_items:
    - 30-elasticsearch-output.conf
  when: logstash_install_input_output
  notify: restart logstash

- name: Install logstash.yml
  template:
    src: logstash.yml.j2
    dest: "/etc/logstash/logstash.yml"
    force: yes
    owner: logstash
    group: logstash
    mode: 0644
