---
- name: Add Elasticsearch GPG key.
  rpm_key:
    key: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: RedHat - add Elasticsearch repo
  become: yes
  template: src=logstash.repo.j2 dest=/etc/yum.repos.d/logstash-{{ es_major_version }}.repo

- name: RedHat - Install Logstash
  become: yes
  yum: name=logstash{% if logstash_version is defined and logstash_version != ""  %}-{{ logstash_version }}{% endif %} state=present update_cache=yes
  register: redhat_logstash_install_from_repo
  notify: restart logstash
  until: '"failed" not in redhat_logstash_install_from_repo'
  retries: 5
  delay: 10
