---
- name: Check if X-pack is already installed
  command: >
    ./bin/logstash-plugin list
    chdir=/usr/share/logstash
  register: logstash_plugins_list
  changed_when: false

- name: Install x-pack.
  command: >
    ./bin/logstash-plugin install x-pack
    chdir=/usr/share/logstash
  when: "'x-pack' not in logstash_plugins_list.stdout"
  notify: restart logstash
